(lang dune 3.16)
(name day1)
(generate_opam_files false)
(formatting
 (enabled_for ocaml))

(package
 (name day1)
 (depends ocaml dune stdio))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
