(lang dune 3.16)
(name day1)
(generate_opam_files false)

(package
 (name day1)
 (depends ocaml dune))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
